<a href="https://colab.research.google.com/github/sandy100061/MachineLearningAssignment/blob/main/Assignment3/Code/Question%20b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as npy;

# 1.b compute the eigenvalues and right eigenvectors of a given square array
array = npy.random.randint(1, 20, (4, 3), dtype=npy.int32)
print ("1.b Array: \n", array)
print ("1.b Array shape: ", array.shape)
print ("1.b Array type: ", type(array))
print ("1.b Array data type: ", array.dtype)

newArray = npy.array([[3, -2], [1, 0]])
eigenvalues, eigenvectors = npy.linalg.eig(newArray)
print ("1.b Eigenvalues: \n", eigenvalues)
print ("1.b Eigenvectors: \n", eigenvectors)

1.b Array: 
 [[14  6 18]
 [17 18  7]
 [19  2  6]
 [14  6 16]]
1.b Array shape:  (4, 3)
1.b Array type:  <class 'numpy.ndarray'>
1.b Array data type:  int32
1.b Eigenvalues: 
 [2. 1.]
1.b Eigenvectors: 
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
